//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zarrin
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelTime
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public Nullable<int> PersonnelID { get; set; }
        public string ZarrinPersonnelCode { get; set; }
        public string PersonnelName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ShamsiDate { get; set; }
        public string Time { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
